const backendData = [
    {
        "id": 1,
        "FormalName": "IEC 62196-3 Configuration AA",
        "Title": "CHAdeMO",
      "stars": "5",
      "colour": "#5DFFA2",
      "comments": "Free charge, need cable type 1 to 2. Thank you !",
    },
    {
        "id": 2,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "1",
        "colour": "#FFDED1",
        "comments": "This charge point has not been working / out of order for over 9 months now. Very disappointing!",
    },
    {
        "id": 3,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "1",
        "colour": "#FD4D00",
        "comments": "Try to avoid the genie chademo 50kW point it will trip n mess up your ev sysyem your EV petrol pump is all good",
      },
      {
        "id": 4,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "5",
        "colour": "#5DFFA2",
        "comments": "Really easy to use, and charged at 45 kW for my Nissan leaf, successful charge using the app. And nice to be able to see charging progress in the app while i was away from the car.",
      },
      {
        "id": 5,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "1",
        "colour": "#FD4D00",
        "comments": "Plugged into number one. App didn't work but charger 2 worked ok with a bank card. Middle of lunch, noticed car had stopped charging.  Returned to find charger showing fault. Have changed to other charger, app still not working. First 2 cards not accepted, third time lucky.",
      },
      {
        "id": 6,
        "FormalName": "IEC 62196-3 Configuration AA",
        "Title": "CHAdeMO",
        "stars": "5",
        "colour": "#5DFFA2",
        "comments": "This was my first attempted use of InstaVolt, and it was  my first successful DC charge. Previuos chargers (2) had failed. Your charge process was so simple and easy. You have restored my faith in the concept of electric travel, thank you.",
      },
      {
        "id": 7,
        "FormalName": "IEC 62196-3 Configuration AA",
        "Title": "CHAdeMO",
        "stars": "4",
        "colour": "#B9E3FF",
        "comments": "Quick, simple, and available. Sadly, the site was very muddy and needs attention.",
      },
      {
        "id": 8,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "4",
        "colour": "#B9E3FF",
        "comments": "Only used the charge point which is not signposted but at the rear of the property as you drive out. The charger worked fine, no issues and there is a restroom within the shop",
      },
      {
        "id": 9,
         "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "5",
        "colour": "#5DFFA2",
        "comments": "Good",
      },
      {
        "id": 10,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "1",
        "colour": "#FD4D00",
        "comments": "Several people wanting to charge cars without success. On the phone to BP for 55 minutes with constant 'please hold' instructions and little reassurance or listening. BP Chargemaster - get your customer service right please!!",
      },
      {
        "id": 11,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "5",
        "colour": "#5DFFA2",
        "comments": "Quick, easy and it worked!",
      },
      {
        "id": 12,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "5",
        "colour": "#5DFFA2",
        "comments": "First Rate charging Station",
      },
      {
        "id": 13,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "2",
        "colour": "#FFE0B2",
        "comments": "long queue at the charging point and no others in the area",
      },
     {
         "id": 14,
         "FormalName": "IEC 62196-3 Configuration AA",
         "Title": "CHAdeMO",
        "stars": "4",
        "colour": "#B9E3FF",
        "comments": "brillant service",
      },
    { 
        "id": 15,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "2",
        "colour": "#FFE0B2",
        "comments": "The parking area is a bit tight, but with all the bells and whistles on the Tesla it is definitely manageable",
      },
      {
        "id": 16,
        "FormalName": "IEC 62196-2 Type 2",
        "Title": "Type 2 (Socket Only)",
        "stars": "5",
        "colour": "#5DFFA2",
        "comments": "Great charger! Not crowded. Walking distance to a larger gas station store with clean bathrooms.",
      },
     {
        "id": 17,
        "FormalName": "IEC 62196-3 Configuration AA",
        "Title": "CHAdeMO",
        "stars": "4",
        "colour": "#B9E3FF",
        "comments": "Great charger! Super fast speeds.",
      }
]

export default backendData;